Avoid distributed node name clash
Errors are like this:

    17:19:23.938 [error] Failed to run bike_data_convertor.
    Error: Protocol 'inet_tcp': the name automedia@foo seems to be in use
    by another Erlang node